### ISSUE TITLE
可靠UDP模式使用问题

### ISSUE THREAD

**Issue by yanche521** [zhllxt/asio2#10]
你好：
我在使用可靠UDP的时候，发现一个这样的问题：启动了client和server，然后我直接关闭了client或server，在重新启动一个对应的client或server，发现不会重新连接，而且等待的时间特别长。也就是说当一个client或者server异常崩溃后，收不到对应的断开信号，我试了一下tcp的那个，tcp那个就可以，断开后，直接在启动，会自动连接上。
想问一下udp的可靠传输下，这个问题怎么解决？

**Comment by zhllxt** [comment]
已修复此问题.
