### ISSUE TITLE
关于同步调用的线程问题

### ISSUE THREAD

**Issue by bitTalk1** [zhllxt/asio2#11]
rpc server/client 的同步调用call 是不是只能在创建对象的线程调用 ，或者说是不是不能在任意的线程中调用 ？
因为_do_call 里面有个断言
// Unable to invoke synchronization rpc call function in communication thread
ASIO2_ASSERT(false);
ec = asio::error::operation_not_supported;

请教一下 这个同步调用对调用线程有什么要求？

**Comment by zhllxt** [comment]
// Unable to invoke synchronization rpc call function in communication thread
RPC的同步调用"call"不能在通信线程中调用，除此之外，在其它任意线程中都可以调用。
通信线程指的是asio::io_context对应的线程，一般来说回调函数都在通信线程中。
`.bind_recv([](...)
		{
			// 这里就是通信线程
		}).bind_connect([](...)
		{
			// 这里就是通信线程
		}).bind_disconnect([]()
		{
			// 这里就是通信线程
		})
`

**Comment by bitTalk1** [comment]
谢谢解答
