### ISSUE TITLE
关于 rpc异步调用的接收顺序问题

### ISSUE THREAD

**Issue by bitTalk1** [zhllxt/asio2#13]
rpc client/server 连接建立后
在client端用async_call 调用同一个方法，在server端的接收顺序是随机的还是按client端的调用顺序到达的？

如果client端在同一个线程用async_call 连续多次调用同一个方法，在server端的接收顺序是否按调用顺序到达？

**Comment by zhllxt** [comment]
无论是server还是client 都是严格按照发送请求的顺序来接收回复的 其实这也没啥好说的 因为是基于tcp 发送顺序和接收顺序已经由 tcp保证了 框架本身也是按照tcp的发送和接收顺序来处理的 没有其它的会改变顺序的代码流程

**Comment by bitTalk1** [comment]
接收端是不是只有一个线程执行被调用函数的？

**Comment by zhllxt** [comment]
接收端是不是只有一个线程执行被调用函数的？client端是，server端不完全是。（注意：client和server都可以调用对方的rpc函数，并不是只有client能调用server端的rpc函数）

server端启动时会创建cpu*2数量的线程，client端启动时会创建1个线程

因此，client端一定是只有一个线程执行被调用函数。

而在server端：假如有1000个client连接到了server，那么这1000个连接被平均分配在了cpu*2数量的线程中。所以client A 在server端可能在线程1中，client B 在server端可能在线程2中，因此server端有cpu*2个线程执行被调用函数。但是对于client A发过来的rpc调用，将永远在server端的线程1中触发，client B 永远在server端的线程2中触发。不会出现client A发过来的rpc调用，在server端一会在线程1中触发，一会儿在线程2中触发这种情况 。

**Comment by zhllxt** [comment]
如果你想让server只在一个线程中执行被调用函数也可以，server端的构造函数都支持传入一个参数：并发线程数量（等同于IOCP的线程池数量），你传1就行了，默认是cpu  *  2

**Comment by bitTalk1** [comment]
谢谢耐心的解答。
