### ISSUE TITLE
RPC模式，使用其他客户端向rpc服务端发送任意字符串，rpc服务端会崩溃

### ISSUE THREAD

**Issue by bitTalk1** [zhllxt/asio2#14]

**Comment by zhllxt** [comment]
已发现此问题，新版已修复此问题，你可以暂使用临时解决方案：
修复 rpc_recv_op.hpp 文件：
`
			try
			{
				dr.reset(s);
				dr >> head;
			}
			catch (cereal::exception&)
			{
				set_last_error(asio::error::message_size);
				derive._do_disconnect(asio::error::message_size);
				return;
			}
			// bug fixed : illegal data being parsed into string object fails to allocate
			// memory due to excessively long data
			catch (std::bad_alloc&)
			{
				set_last_error(asio::error::message_size);
				derive._do_disconnect(asio::error::message_size);
				return;
			}
			catch (std::exception&)
			{
				set_last_error(asio::error::message_size);
				derive._do_disconnect(asio::error::message_size);
				return;
			}

`

**Comment by zhllxt** [comment]
v2.6版本已修复此问题.
注意，RPC的接口有以下改动：
1、以前启动rpc的函数是start("0.0.0.0", "8080", asio2::use_dgram); 现在改为start("0.0.0.0", "8080");删除了第三个参数(框架内部会自动处理此参数)，因为我自己在使用过程中总是会忘写第三个参数。
2、以前设置rpc默认超时的函数是timeout(...);现在改为default_timeout(...);为什么要这样改，是为了给下面第3条让路。
3、以前调用rpc函数的方式是async_call([](...){}, std::chrono::seconds(3),  "add", 12, 21);其中第一个参数是回调函数，第二个参数是超时时间，第三个及后面的参数是RPC函数的名字和参数。我自己在使用过程中经常容易把参数的位置搞混淆，不知道哪个参数在前，哪个参数在后，心智负担很大。现在添加了链式调用功能解决这个问题，如：
client.timeout(std::chrono::seconds(5))
         .async_call("mul", 2.5, 2.5)
         .response(
	[](asio::error_code ec, double v)
{
	std::cout << "mul1 " << v << std::endl;
});
妈妈再也不用担心我把参数位置写错了。
