### ISSUE TITLE
android gcc无法编译

### ISSUE THREAD

**Issue by RealMG** [zhllxt/asio2#16]
报错出现在：
\beast\core\detail\config.hpp:36:4: error: Beast requires C++11: gcc version 4.8 or later needed

检查Android ndk版本，gcc为4.9.

更换nkd版本，并手动指定gcc版本为4.9同样报这个错误。

**Comment by FuChengYiXiao** [comment]
> 报错出现在： \beast\core\detail\config.hpp:36:4: error: Beast requires C++11: gcc version 4.8 or later needed
> 
> 检查Android ndk版本，gcc为4.9.
> 
> 更换nkd版本，并手动指定gcc版本为4.9同样报这个错误。

Hi，这个问题怎样解决的？
