### ISSUE TITLE
iopool 是否应提取出来！

### ISSUE THREAD

**Issue by ghchris** [zhllxt/asio2#19]
一个服务进程会同时出现tcpsever，tcpclient等业务场景，他们可以公用一个iopool。

**Comment by zhllxt** [comment]
我感觉这个功能意义不太大，主要是我觉得来使用这个框架的用户基本上是普通用户，如果是高端用户的话，他们也不会用这个框架而是自己去实现了。
我想了想，加这个功能还有点复杂，现在iopool和整个框架耦合度很高，即使加上这个功能，但会用到的这个功能的可能少之又少，先放一放吧，后面再看。

**Comment by zhllxt** [comment]
master分支下的最新代码已经支持此功能了，示例在example/custom_scheduler/custom_scheduler.cpp
