### ISSUE TITLE
get_io_context函数在高版本asio中被删除

### ISSUE THREAD

**Issue by Kcass774** [zhllxt/asio2#2]
Asio 1.14.0 / Boost 1.70中删除了这个函数
[boost的更新日志](https://www.boost.org/doc/libs/1_71_0/doc/html/boost_asio/history.html#boost_asio.history.asio_1_14_1___boost_1_71)

> The previously deprecated get_io_context and get_io_service member functions have now been removed.

**Comment by Kcass774** [comment]
改用get_executor即可解决问题:D

**Comment by zhllxt** [comment]
已修复 thks

**Comment by Kcass774** [comment]
使用get_executor().context()会导致奇怪的编译报错
![Snipaste_2019-09-28_16-32-18](https://user-images.githubusercontent.com/42107284/65813953-45348480-e20e-11e9-90f6-86c6656cbb60.png)
而直接用get_executor()就不会.
用boost1.71.0/1.70.0测试了都报错,其他版本不清楚

**Comment by zhllxt** [comment]
再次修复（用boost 1.68.0和1.70.0及asio 1.12.2 standalone进行了测试）

很惭愧，初次更改后没有去做测试，对你这种细心和严谨的态度表示敬佩！
