### ISSUE TITLE
如何设置通过指定dns解析域名地址？

### ISSUE THREAD

**Issue by jococi** [zhllxt/asio2#21]
如题

**Comment by zhllxt** [comment]
:(
不知道， 我看了下asio的api，应该不支持这个功能。

**Comment by RealMG** [comment]
应该是先用其它的DNS库解析，再用这个库传输吧？

**Comment by jococi** [comment]
> 应该是先用其它的DNS库解析，再用这个库传输吧？
嗯，只能用这个方法了。asio2应该用了系统的解析函数
