### ISSUE TITLE
Android下编译错误

### ISSUE THREAD

**Issue by FuChengYiXiao** [zhllxt/asio2#22]
使用Android Studio集成JNI工程时，beast/core/detail/config.hpp:36 检测到__GNUC__版本过低，这个有解决办法吗？NDK版本 21.4.7075529

**Comment by zhllxt** [comment]
我记得这个问题解决过了啊，我在ndk-r22b下都编译测试过了。
如果你还是存在这个问题，你有两个解决办法：
1、下载最新的master分支的代码(今天是2021年12月07日)，最新的master分支的代码做了大量调整，修改了一些BUG。
2、直接把beast/core/detail/config.hpp这个文件里那个报错的代码注释起来。
我们的程序在安卓下都跑起来了，包含了http websocket.所以beast这个问题肯定是已经处理过了，只不过东西太多，我怕还是有疏漏。

**Comment by FuChengYiXiao** [comment]
你好，这个问题是clang编译器导致的，Mac和iOS平台可能绕过Android的宏定义检查。在StackOverflow找到了一篇讨论，此外，asio中单独处理了__clang__这个宏。
https://stackoverflow.com/questions/38499462/how-to-tell-clang-to-stop-pretending-to-be-other-compilers

**Comment by zhllxt** [comment]
已修复
直接将boost库的宏检测移植过来了（现在仍然是header only的，不依赖boost库，做了移植改造），以后不再自己处理这些琐碎且难以找环境测试的问题了。
