### ISSUE TITLE
asio2/http/detail/http_parser.h编译错误

### ISSUE THREAD

**Issue by FuChengYiXiao** [zhllxt/asio2#23]
asio2/http/detail/http_parser.h:535 
state类型强制转换，主干分支已修改，但是发布的V2.7版本没有合入，查看发布记录存在文件冲突。
commits 7afc2c27158fa71dd24df4dbfa047ff6adca2b7d

**Comment by zhllxt** [comment]
请下载最新的master分支代码（今天是20211207）

**Comment by zhllxt** [comment]
master分支代码相对于2.7版的代码，API和功能有变更，主要是原来的send函数改为了async_send和send两个函数。以后不会再更新和修复2.7版本的代码或问题了。
所以请使用master分支代码，有使用问题上QQ群问或直接看工程中的example。

**Comment by FuChengYiXiao** [comment]
好的，非常感谢。
