### ISSUE TITLE
是否有支持使用boost内的asio和beast的计划

### ISSUE THREAD

**Issue by nevermoreluo** [zhllxt/asio2#25]
看代码里面有ASIO_STANDALONE ,  
但是提示`// Must define ASIO_STANDALONE, otherwise compilation fails.`   
询问一下有支持这部分的计划嘛？

**Comment by zhllxt** [comment]
develop分支里的最新代码已经支持。

**Comment by zhllxt** [comment]
用boost的话要把config.hpp中的ASIO_STANDALONE和BEAST_HEADER_ONLY两个宏都要注释起来。

早期的版本本来是支持boost的，后来为了实现header only的beast（header only的http和websocket），就对boost::beast进行了改造，改造过程中发现，兼容boost挺麻烦，就没再管boost的了，近段又重新撸了一遍，对boost的也做了支持。

**Comment by zhllxt** [comment]
用boost的话要把config.hpp中的ASIO_STANDALONE和BEAST_HEADER_ONLY两个宏都要注释起来。

早期的版本本来是支持boost的，后来为了实现header only的beast（header only的http和websocket），就对boost::beast进行了改造，改造过程中发现，兼容boost挺麻烦，就没再管boost的了，近段又重新撸了一遍，对boost的也做了支持。

**Comment by nevermoreluo** [comment]
thx 万分感谢
