### ISSUE TITLE
Feat Request:  希望能实现一个动态扩容的buffer，带对象池的那种，提高效率

### ISSUE THREAD

**Issue by jaysunxiao** [zhllxt/asio2#29]
在java的netty中内部实现了buffer的对象池，需要用的时候拿一个出来，这样buffer的回收都不用了

组包经常会用到自动扩容

**Comment by zhllxt** [comment]
如果目的是为了“带对象池的那种，提高效率”，我觉得没必要，直接用tcmalloc,mimalloc之类的就够了。
