### ISSUE TITLE
使用例程中的http服务，建立websocket连接时发生Assertion failed

### ISSUE THREAD

**Issue by supf1994** [zhllxt/asio2#31]
将asio2\example\http\server中的http服务例程编译，当采用debug启动时，在建立websocket连接时将会发生Assertion failed，而采用release时便可以正常运行

Assertion failed: derive.sessions().io().strand().running_in_this_thread(), file D:\Develop\Lib\asio2\asio2\http\component\ws_stream_cp.hpp, line 83

**Comment by zhllxt** [comment]
这是一个BUG，develop分支的代码早前已经修复过这个问题。

使用develop分支的代码，这个分支持续在更新并修复了很多问题，以后会用develop分支代码发布release版。
