### ISSUE TITLE
关于异步操作使用strand的疑问

### ISSUE THREAD

**Issue by supf1994** [zhllxt/asio2#32]
最近在拜读源码，对于每个tcp连接绑定一个io对象，一个io对象会同时创建一个strand并且只运行于一个线程中，所有tcp异步操作都会在绑定的ioc线程中执行并且使用strand，如果ioc只运行于单线程的情况下应该不存在线程竞争，那为何要使用strand？这里想不明白

**Comment by zhllxt** [comment]
这个问题之前也有网友问过，框架是one context per thread的模式，的确可以不用strand，只是早期我对asio也没有足够熟悉，所以在最初的代码里使用了strand，后来再更新升级时，也没有再删掉strand。

**Comment by zhllxt** [comment]
具体在asio2这个这个框架里，strand到底有没有其它实际作用，我已经记不清了。但是有一个作用是，用来测试框架的某个流程逻辑是否在其应该在的线程中，就类似这样的代码：ASIO2_ASSERT(this->sessions().io().strand().running_in_this_thread());

**Comment by zhllxt** [comment]
最新版本代码已经完全删除了strand，因为由于strand的实现问题导致跨模块时（如exe和dll）使用strand.running_in_this_thread()判断会不正确。
