### ISSUE TITLE
请问多个client是共享同一个io context还是多个client各对应一个io context？

### ISSUE THREAD

**Issue by berry0511** [zhllxt/asio2#37]
我现在大概在一个电脑里起动大约300个左右的client，数据处理速度要求比较高，所以想问下是在一个io里面处理所有的client回调吗

**Comment by zhllxt** [comment]
默认情况下每个client一个独立的io context，每个io context一个独立的线程

但如果你有1万个client，不可能启动1万个线程，参考example中shared_iopool示例，让多个client共享io context

**Comment by berry0511** [comment]
好的，非常棒的仓，感谢分享

**Comment by famik** [comment]
用异步的，感觉一个线程就够了

**Comment by famik** [comment]
> 默认情况下每个client一个独立的io context，每个io context一个独立的线程
> 
> 但如果你有1万个client，不可能启动1万个线程，参考example中shared_iopool示例，让多个client共享io context

用异步的，感觉一个线程就够了
