### ISSUE TITLE
udp 怎样获取应答数据？

### ISSUE THREAD

**Issue by uvwz** [zhllxt/asio2#39]
udp client  通过 send 发送消息后
怎样在当前线程获取server端对该消息返回的数据？

**Comment by zhllxt** [comment]
这个是异步框架，不支持这个功能。
接收数据只能在bind_recv的回调函数中去获取。

**Comment by uvwz** [comment]
rpc 框架里面可以添加udp方式吗？

**Comment by zhllxt** [comment]
我偷偷的告诉你，你不要告诉别人哈。
其实之前我做过这个功能，但是由于我认为该实现过于扭曲，而且效率低，所以后来我在博客的公开文章上把这个使用方法删除了，但框架其实还是支持的。
如果你本身对收发数据的效率需求并不高，你完全是可以使用该功能的。
下面针对你的情况，我举个简单的例子：
asio2::rdc::option rdc_option
{
	[](std::string_view)
	{
		return 0;
	}
};

asio2::udp_client client;

client.start("127.0.0.1", 18037, rdc_option);

std::string response = client.call<std::string>("some message");

关于这个用法的具体说明可以参考：asio2/doc/blog/zh-cn/rdc.md

**Comment by uvwz** [comment]
很强大的框架，非常感谢。
