### ISSUE TITLE
http server支持大文件上传和下载吗

### ISSUE THREAD

**Issue by berry0511** [zhllxt/asio2#44]
RT

**Comment by zhllxt** [comment]
http server - 下载支持，上传不支持
http client - 都支持

**Comment by berry0511** [comment]
好的，下载是通过rep.fill_file实现的吗？

**Comment by zhllxt** [comment]
是的
大文件最好加上chunk标志
rep.chunked(true);

**Comment by berry0511** [comment]
好的，感谢

**Comment by famik** [comment]
> http server - 下载支持，上传不支持 http client - 都支持

http client 上传大文件怎么实现呢？

**Comment by zhllxt** [comment]
每次默认读取4096字节。
