### ISSUE TITLE
qt 和vs2017下编译异常

### ISSUE THREAD

**Issue by gitthb** [zhllxt/asio2#45]
qt5.9.8下提示需要c++17，在pro文件中配置了config+=c++17也没有用。在vs2017下可以编译，但智能提示用不了，凡是引用了asio2的都用不了智能提示，编译也有智能提示方面的错误；代码编辑界面上很多函数和变量都飘红。

**Comment by zhllxt** [comment]
1. QtCreator 打开 CMake 的工程，设置set(CMAKE_CXX_STANDARD 17)可以正常编译，而且我记得有群友也有在qt 的 pro 文件中配置的，也没有问题。
2. vs2017的智能提示用不了，这是由于新版本的asio在vs2017下的智能提示用不了，这个问题解决不了，用vs2022吧，没有这个问题。

**Comment by gitthb** [comment]
在pro里面配置的样本有没有呢

**Comment by zhllxt** [comment]
由于我基本从没使用过QT，经过测试：

在Qt Creator 8.0.1下新建Qt Widgets Application

编译命令有如下字眼：正在启动 "C:\Qt\Tools\mingw1120_64\bin\mingw32-make.exe" clean -j16

所以编译器应该是mingw32-make.exe

pro配置文件的完整内容是：

```cpp
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

// 下面一行是我手工添加的
QMAKE_CXXFLAGS += "-Wa,-mbig-obj"

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    main.cpp \
    mainwindow.cpp

HEADERS += \
    mainwindow.h

FORMS += \
    mainwindow.ui

// 下面两行是我手工添加的
INCLUDEPATH += D:/asio2/3rd
INCLUDEPATH += D:/asio2/include

// 下面两行是我手工添加的
LIBS += -lws2_32
LIBS += -lmswsock

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target
```

在Release模式下可以编译成功，Debug下编译报错，报错内容是：file too big；关于file too big这个问题我在clion下遇到过，在mingw编译下总是会出现这个错误，错误原因应该是由于模板代码膨胀导致的，我暂时解决不了，其它编译器如msvc gcc clang均没有这个错误。

**Comment by zhllxt** [comment]
关于
LIBS += -lws2_32
LIBS += -lmswsock
这两行链接库的问题，可以参考/asio2/example/CMakeLists.txt中GENERAL_LIBS和OPENSSL_LIBS这两个变量的内容，他们就是各个操作系统下要链接的系统网络库文件。
