### ISSUE TITLE
execution_work_guard没有重载函数可以转换所有参数类型（asio新版本）

### ISSUE THREAD

**Issue by obqrn** [zhllxt/asio2#49]
asio2\include\asio2\bho\beast\core\async_base.hpp(246): error C2665: “bho::beast::detail::execution_work_guard<Executor>::execution_work_guard”: 没有重载函数可以转换所有参数类型
报这个错。
使用asio-1-27-0才会出现
用asio-1-26-0不会

**Comment by zhllxt** [comment]
已修复，在develop分支，一段时间之后会合并到master。
