### ISSUE TITLE
一个IO监听多个端口怎么处理

### ISSUE THREAD

**Issue by kerwinzxc** [zhllxt/asio2#5]
一个IO监听多个端口怎么处理

**Comment by zhllxt** [comment]
你指的是一个io_context还是一个socket啊？
如果是一个io_context，你搞多个socket用这同一个io_context，然后多个socket绑定不同的端口就行了吧。但这个asio2并没有做io_context绑定多个端口的功能，实际上，这个框架已经把io_context这个细节包装起来了，用户层是感受不到io_context这个东西的存在的。
如果是一个socket，似乎不行，同一个socket应该是只能绑定到一个端口。

**Comment by kerwinzxc** [comment]
对，我的意思就是一个 io_context 绑定多个端口的功能，服务器中可能需要监听多个端口

**Comment by zhllxt** [comment]
这个好办，多个SOCKET是可以使用一个io_context的，这多个SOCKET分别绑定不同端口即可。
这个框架里没有这个功能，你去找找asio的示例看看就明白了，比较简单的，自己再写下就行。
