### ISSUE TITLE
http client使用ip请求报错

### ISSUE THREAD

**Issue by xiaonaiquan** [zhllxt/asio2#50]
使用Http client请求内网接口，报错400 ：

<p>Your browser sent a request that this server could not understand.<br />
Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />
 Instead use the HTTPS scheme to access this URL, please.<br />
</p>

我的使用方式：
        std::string url = "https://192.168.2.3/aaaaaa";
        http::web_request req2 = http::make_request(url);
        req2.method(http::verb::get);
       auto rep2 = asio2::http_client::execute(req2);

以上请求，使用curl或者postman是可以请求到内容的。

**Comment by zhllxt** [comment]
改为 asio2::https_client::execute(req2); 即可

asio2::http_client::execute(req2); 只能处理http请求，不能处理https请求。

**Comment by zhllxt** [comment]
另：你上面的代码有点重复，直接 auto rep2 = asio2::https_client::execute("https://192.168.2.3/aaaaaa");即可，支持直接传入url字符串

**Comment by xiaonaiquan** [comment]
> 改为 asio2::https_client::execute(req2); 即可
> 
> asio2::http_client::execute(req2); 只能处理http请求，不能处理https请求。

忘记看sll的ｄｅｍｏ了，抱歉
