### ISSUE TITLE
http服务手动应答的问题

### ISSUE THREAD

**Issue by obqrn** [zhllxt/asio2#52]
示例代码，创建http服务，相同client（tcp）链路多次请求，第二次服务就收到数据了。使用的异步http服务。

**Comment by zhllxt** [comment]
什么意思，我没明白？

**Comment by obqrn** [comment]
用postman试下，就是发送第二次就不行了， 看了下是客户端的http链路没断，一直用这条链路发http请求。

**Comment by zhllxt** [comment]
已修复，在develop分支，一段时间之后会合并到main分支。
