### ISSUE TITLE
rpc问题

### ISSUE THREAD

**Issue by ghchris** [zhllxt/asio2#6]
在绑定的函数里面调用async_call会异常，会导致OnRegister函数调用两次，SetSessionID返回失败
![image](https://user-images.githubusercontent.com/12080243/69518162-cc457500-0f91-11ea-875f-9c8077483221.png)
![image](https://user-images.githubusercontent.com/12080243/69518201-e8e1ad00-0f91-11ea-9513-088bf06b515c.png)

**Comment by zhllxt** [comment]
这个嵌套调用出错的流程如下：
1、服务端接收到rpc调用请求，解析请求，在解析请求的同时用序列化对象sr_来构造回复包的头部（回复包的构造需要多个步骤）
2、调用rpc请求所指定的函数，在该业务函数中又嵌套调用了rpc函数，于是又开始用序列化对象sr_构造请求包
关键点在于第2步中构造请求包和第1步中构造回复包使用的是同一个序列化对象sr_，于是问题产生。

解决办法有两个：
一：在每次调用call或async_call函数中单独声明一个临时serilizer对象sr
二：强制call或async_call函数中的send操作必须是异步执行的（现在是：如果发现call或async_call是在io_context线程中被调用的，则直接调用了send）

我采用的解决办法是二，当初为什么在序列化时没有声明临时对象sr而统一用的成员变量sr_，就是为了减少内存分配，一个serializer对象我记得好像将近100byte。
办法一二各有长短吧，具体哪个效率更好有待测试。

**Comment by ghchris** [comment]
RPC server端能否知道对应client调用的session，很多业务场景是需要知道哪个client调用了server端的服务

**Comment by zhllxt** [comment]
你说的有道理哦，这个需求应该是常规硬性需求，使用场景应该非常多。我考虑考虑。

**Comment by zhllxt** [comment]
你有没有看过别的RPC框架，有支持你这个需求的么，举几个例子我参考一下呗，毕竟参考成熟的东西做出来也更好些。

**Comment by zhllxt** [comment]
已解决，请看示例/demo/src/rpc_server.hpp

**Comment by ghchris** [comment]
还是会有问题！同一个client连续async_call 3次 如果在server端sleep 1秒 会导致后面两次接收不到结果
![image](https://user-images.githubusercontent.com/12080243/70134198-8fc8f600-16c2-11ea-845f-406b3f7c3843.png)
![image](https://user-images.githubusercontent.com/12080243/70134230-9fe0d580-16c2-11ea-8797-33cea8582079.png)
![image](https://user-images.githubusercontent.com/12080243/70134248-a66f4d00-16c2-11ea-80f7-a2959c395a23.png)
