### ISSUE TITLE
多线程ICMP

### ISSUE THREAD

**Issue by QQ2017** [zhllxt/asio2#60]
将如下同步ping封装到DLL中给其他语言调用，在多线程并发ping中，返回的ping结果大概率是ping不通，实际上可以ping通，不知是否有过类似测试？
`std::cout << asio2::ping::execute("www.baidu.com").milliseconds() << std::endl;`

**Comment by zhllxt** [comment]
实际上asio的icmp协议支持非常不成熟，我测试过在linux系统下icmp无法使用，表现就是ping永远失败。

见：https://github.com/chriskohlhoff/asio/issues/781

封装在DLL中使用的这种方式，我没测试过。
