### ISSUE TITLE
The encoding and line break problems of printing characters in function `asio2::last_error_msg().c_str()`

### ISSUE THREAD

**Issue by sirlis** [zhllxt/asio2#61]
Dear developer @zhllxt @astr0mfly :

I am using your excellant codes on windows 11 with mingw64 latest version.

I tried to setup a socket server using the example code in https://github.com/zhllxt/asio2/blob/main/example/tcp/server/general/tcp_server_general.cpp
and the printing problem seems to be with

```cpp
printf("start tcp server : %s %u %d %s\n",
            server.listen_address().c_str(), server.listen_port(),
            asio2::last_error_val(), asio2::last_error_msg().c_str()); })
```
when starting the server, it will print information but with problems:

![image](https://github.com/zhllxt/asio2/assets/12960298/59a4ec99-439c-4905-bcec-d8c9cf8e678a)

The client is setup using https://github.com/magicdam/MagicSocketDebugger/releases

1) `asio2::last_error_msg().c_str()` return `0x28022070dc0 "�����ɹ���ɡ�\r\n"`, maybe they are gbk strings? By the way, all other chinese characters are printed correctly, for example the `测试` in the screenshot.
2) `asio2::last_error_msg().c_str()` already has `\r\n`, which will cause an extra empty line when ending the `printf` text with `\n`. But all other `printf` calls in `tcp_server_general.cpp` have no extra empty line problem.

**Comment by zhllxt** [comment]
This must be a coding issue with your server.
As for how to solve it, you need to test it yourself because this issue is related to your system environment.
Why other chinese characters are printed correctly, for example the ```测试``` in the screenshot? beacuase the characters of ```测试``` is not generated on the server, but sent by the client.

**Comment by sirlis** [comment]
> This must be a coding issue with your server. As for how to solve it, you need to test it yourself because this issue is related to your system environment. Why other chinese characters are printed correctly, for example the `测试` in the screenshot? beacuase the characters of `测试` is not generated on the server, but sent by the client.

got it , thank you
