### ISSUE TITLE
当 服务端 或者客户端一方 不是c++时 是否有example示例

### ISSUE THREAD

**Issue by marklove5102** [zhllxt/asio2#74]
如题,有时候一些老程序想上新代码.可能 客户端或者服务端那边 总有一方不能用c++时..example 如何写 有那个示例是这方面的?

**Comment by zhllxt** [comment]
`客户端或者服务端那边 总有一方不能用c++`

这跟你用C++来写程序没有任何关系，跟你问我的'有那个示例是这方面的'也没有任何关系，不管对方用什么语言，只要他按照你们约定好的协议收发数据即可，你就能和他正常通信。
