### ISSUE TITLE
g++ v7.3.8编译报错 

### ISSUE THREAD

**Issue by ghchris** [zhllxt/asio2#8]
![image](https://user-images.githubusercontent.com/12080243/69955390-801da600-1538-11ea-9cef-10ec56480814.png)

template<typename MatchCondition>
		inline void _handle_accept(const error_code & ec, std::shared_ptr<session_t> session_ptr,
			condition_wrap<MatchCondition> condition)
		{
			set_last_error(ec);

			// if the acceptor status is closed,don't call _post_accept again.
			if (ec == asio::error::operation_aborted)
			{
				this->derived()._do_stop(ec);
				return;
			}

			if (!ec)
			{
				if (this->is_started())
				{
					session_ptr->counter_ptr_ = this->counter_ptr_;
					session_ptr->start(condition);
				}
			}

			this->derived()._post_accept(std::move(condition));
		}
这里明显counter_ptr_和start 是session_ptr的protected不能调用吧

**Comment by ganggangliu** [comment]
同样遇到，自己改了下！

**Comment by zhllxt** [comment]
不好意思，看来是编译器版本的差异，我在GCC8.2.0下编译是没有问题的。

理论上应该是不报错才对的，因为在
tcp_session_impl_t
类的开头有对友员类的声明
template <class, class>               friend class tcp_server_impl_t;

这样server应该是可以直接访问session类的protected的变量的。

**Comment by zhllxt** [comment]
已修复此问题！
